### ISSUE TITLE
Incorred i2c address for left and right PCA9685

### ISSUE THREAD

**Issue by ikigai-festuccia-simone** [rookidroid/hexapod#1]
there is a problem with the wiring schema and the code for arduino board regarding the addressing of the 2 controllers

on the wiring schema is marked to solder the a5 connector that's dec 32 hex 20

in the code for arduino board reference is 41 for the second channel, in this way half of the hexapod doesnt move. changing the address to x60 will have all the servos to move correctly!

another issue is that on the source code the standard address is left for the left legs and override i2c is for the right, in the wiring schema is the opposite.

**Comment by rookiepeng** [comment]
Thanks for pointing out the mistakes. I have corrected the diagram
