### ISSUE TITLE
leg joint mounting scheme should be 3x (L) and 3x (R) instead of 6x

### ISSUE THREAD

**Issue by ikigai-festuccia-simone** [rookidroid/hexapod#2]
hi, since I see you are pretty active on the project, I would like to point out another thing that can lead to confusion on the mounting scheme.

there is a mounting guide that show 6 time the same joint but they should be two different series for have the first servo to move the joint allways on top.

**Comment by rookiepeng** [comment]
Thanks! I adjusted the readme to address this
