### ISSUE TITLE
Small raiser for Servo's

### ISSUE THREAD

**Issue by SammieSamSam** [rookidroid/hexapod#3]
I came to the conclusion that for some servo's, the servo becomes slightly raised and not in line with the print. so i made 2mm raisers that are really small, and go in between the servo and the legs. i put the STL and some images in the attachments in the form of a zip file :) hope it helps some people that want to build this hexapod too!
[accessory_small_spacer_mg90s.zip](https://github.com/user-attachments/files/17945919/accessory_small_spacer_mg90s.zip)

**Comment by SammieSamSam** [comment]
I just realized i rescaled the stl im my slicer. sorry! it needs to be 11mmx5mmx5mm :) sorry for the inconvenience!

**Comment by rookiepeng** [comment]
I already have "accessory_spacer_mg90s.STL" in the model. Doesn't it work?

While using MG92B servo, the spacer is not needed. If you use MG90S, the spacer is needed.

**Comment by SammieSamSam** [comment]
I use the MG90s with "accessory_spacer_mg90s.STL" but the servo moves within the leg if i don't also use the small spacers i made (they go in between the top of the servo and the leg like in the image i will also send again)
![Media (3)](https://github.com/user-attachments/assets/512f35b2-c7c0-4f0a-94ef-8b559b98b72e)
I'm not sure if it is an issue with the certain servo's I got having extra space between the screw holes or it being an issue with every MG90s but this spacer works for me in combination with the other spacer :)

**Comment by rookiepeng** [comment]
This is strange. I guess the servo you use has different size with the one I use. Anyway, I will add your stl file into the repo. Thank you!
